import './js/api';
import './js/authorization';
import './js/modal-authorization';
import './js/books-all';
import './js/books-genre';
import './js/categories-list';
import './js/header';
import './js/modal-window';
// import './js/shopping-list';
import './js/support-ukraine';
import './js/mobile-menu';
import './js/array-of-funds';
